spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  web:
    locale-resolver: fixed
    locale: en
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: update